# -*- coding: utf-8 -*-
"""GDof machine learning project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KfegqFtle0EAcugRr792mHzTZtYubNhG
"""
# Now import libraries

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
data = pd.read_csv("train.csv")
data.head(2)

data.head(5)

data.tail(2)

data.info

# the data contains how many columns

data.columns

data.shape

data.isnull().sum()

data.dropna(inplace=True)

data.isnull().sum()

feature_cols = ['id','original_text','lang','retweet_count','sentiment_class']
X = data[feature_cols]
y = data.original_author

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

clf = DecisionTreeClassifier
model_fit = (X,y)

model_fit = (X_train,y_test)

model_fit

